triggers:
   - name: ri-tg1
     type: trigger
     version:
       counter: 3
       
   - name: ri-tg2
     type: trigger
     version:
       counter: 2
       
   - name: ri-tg3
     type: trigger
     version:
       counter: 0
